version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: zip
    name_template: "terraform-provider-jira-automation_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "terraform-provider-jira-automation_{{ .Version }}_SHA256SUMS"
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: "terraform-provider-jira-automation_{{ .Version }}_manifest.json"

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: "terraform-provider-jira-automation_{{ .Version }}_manifest.json"

changelog:
  disable: true
