version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: zip
    name_template: "terraform-provider-jira-automation_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "terraform-provider-jira-automation_{{ .Version }}_SHA256SUMS"

changelog:
  disable: true
